name: 'Generate Build Provenance Statement'
description: 'Generate provenance statement for build artifacts'
author: 'GitHub'

outputs:
  predicate:
    description: >
      The JSON-serialized of the attestation predicate.
  predicate-type:
    description: >
      URI identifying the type of the predicate.
runs:
  using: node20
  main: ../dist/index.js
