# Unordered list style
MD004:
  style: dash

# Ordered list item prefix
MD029:
  style: one

# Line length
MD013:
  line_length: 80
  code_blocks: false
  tables: false
  headings: false
  headings_with_children: false
  code_lines: false
